#!/bin/bash
# a hack-o-script to make my mic work with(out) broken PulseAudio >=1.0

pa=pulseaudio
pkg=$pa{,-alsa}

app_res() {
[[ -n $1 ]] &&
if [[ -n `pidof $1` ]]; then
	killall -TERM $1 && $1 &
else
	$1 &
fi
}

case $1 in

	r) # this here below (pacman) writes to stderr probably, let's get rid of this
	if [[ `pacman -Qq $pa` == "$pa" ]]; then
		$pa -k;
		eval sudo pacman -Rdd --noconfirm $pkg >&-;
		if [[ -n `pidof $pa` ]]; then
			killall $pa;
		fi
		sudo rc.d restart alsa >&-;
		app_res $2
	else
		echo "$pa ain't here";
		exit 1;
	fi
	;;

	i)
	if [[ `pacman -Qq $pa` != "$pa" ]]; then
		eval sudo pacman -S --asdeps --noconfirm $pkg >&-
		$pa -D
		sudo rc.d restart alsa >&-
		app_res $2
	else
		echo "$pa already here";
		exit 1;
	fi
	;;

	*)
	echo 'FK U'
	;;
esac
exit 0
