#!/bin/bash
# a hack-o-script to make my mic work with(out) broken PulseAudio >=1.0

exec 1>/dev/null
exec 2>&1

pa=pulseaudio
pkg=$pa{,-alsa}

app_res() {
do=TERM
[[ -n $1 ]] &&
if [[ -n $(pidof $1) ]]; then
	killall -$do $1 
	if [[ -n $(pidof $1) ]]; then
		do=KILL;
		app_res;
	fi
	$1 &
else
	$1 &
fi
}

case $1 in

	r)
	if [[ $(pacman -Qq $pa) == "$pa" ]]; then
		$pa -k;
		eval sudo pacman -Rdd --noconfirm $pkg;
		if [[ -n $(pidof $pa) ]]; then
			killall $pa;
		fi
		sudo rc.d restart alsa;
		app_res $2;
	else
		echo "$pa ain't here" 1>$(tty);
		exit 1;
	fi
	;;

	i)
	if [[ $(pacman -Qq $pa) != "$pa" ]]; then
		eval sudo pacman -S --asdeps --noconfirm $pkg;
		$pa -D;
		sudo rc.d restart alsa;
		app_res $2;
	else
		echo "$pa is already there" 1>$(tty);
		exit 1;
	fi
	;;

	*)
	echo "Usage:

i - install $pa
r - remove $pa

You can also add a second arg with a program name so it gets restarted after r/i action.

Example: pa r skype" 1>$(tty)
	;;
esac
exit 0
