#!/bin/bash
# automatically replace old checksums with new in PKGBUILDs
# TODO: make it work with several source files (multiline)

exec 2>/dev/null

file=PKGBUILD
if [[ -w $1 ]]; then file=$1; fi
new_sum=$(makepkg -g -p ${file})

if [[ ${new_sum} ]]; then
  if [[ ! $(grep 'sums=(' ${file}) ]]; then
    sed -i "s|^source.*|&\n${new_sum}|" ${file}
  else
    sed -i "s|.*sums=(.*|${new_sum}|" ${file}
  fi
else
  exit 1
fi
